version: '3'
networks:
  mynet:
services:
  nginx:
    image: nginx:1.22.0
    restart: always
    container_name: nginx
    environment:
      # 自定义host
      - XRAY_HOST=${XRAY_HOST}
    ports:
      - 80:80
    networks:
      - mynet
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - xray
  xray:
    image: teddysun/xray:1.5.6
    restart: always
    container_name: xray
    environment:
      # 自定义host
      - XRAY_HOST=${XRAY_HOST}
    ports:
      - 443:443
      - 22220:22220
      - 22226:22226
    networks:
      - mynet
    volumes:
      - ./xray/config.json:/etc/xray/config.json
      # 证书地址
      - /etc/letsencrypt/:/etc/letsencrypt/