version: '3'
networks:
  mynet:
    external: true
services:
  prometheus:
    image: prom/prometheus:v2.46.0
    restart: unless-stopped
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - mynet
    #ports:
    #  - 9090:9090
    expose:
      - 9090
    environment:
      - TZ=Asia/Shanghai
    user: "0"