version: '3.9'
networks:
  mynet:
    external: true
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    ports:
      - 8123:8123
    networks:
      - mynet
    volumes:
      - ./config:/config
    environment:
      - TZ=Asia/Shanghai
      