version: '3'
networks:
  mynet:
    external: true
services:
  nodequery:
    image: jaydenlee2019/mynodequery:latest
    container_name: nodequery
    restart: unless-stopped
    ports:
      - 15000:5000
    networks:
      - mynet
    volumes:
      - ./config/appsettings.json:/app/appsettings.json