version: '3'
networks:
  mynet:
    external: true
services:
  sspanel:
    image: sspaneluim/panel
    container_name: sspanel
    restart: unless-stopped
    ports:
      - 13301:80
    networks:
      - mynet
    volumes:
      - ./config/.config.php:/var/www/config/.config.php

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 13302:80
    networks:
      - mynet
    environment:
      - PMA_ARBITRARY=1