networks:
  mynet:
    external: true
services:
  nginx:
    image: nginx:1.26
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./conf:/etc/nginx/
      - ./logs:/var/log/nginx
      - ./html:/usr/share/nginx/html
      - ${NGINX_SSL_PATH}:/etc/letsencrypt
      - ${NGINX_SSL_PATH}/live/${NGINX_SSL_HOST}:/etc/letsencrypt/ssl/xx
    networks:
      - mynet
    ports:
      - 80:80
      #- 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - TZ=Asia/Shanghai