version: '3'
networks:
  mynet:
    external: true
services:
  nginx:
    image: nginx:1.22.0
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./geo/GeoCountry.dat:/etc/nginx/GeoCountry.dat
      - ./nginx/geo/GeoCity.dat:/etc/nginx/GeoCity.dat
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
      - ./../naiveproxy/conf/cert:/ssl
      - ./../wordpress/html:/wordpress
    networks:
      - mynet
    ports:
      - 80:80
      #- 443:443
    environment:
      HOST: ${HOST}
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - TZ=Asia/Shanghai