version: '3.9'
networks:
  mynet:
    external: true
services:
  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:6.1.0-fpm
    container_name: wordpress
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mynet
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      # 如果需要自定义上传的文件路径修改这里，同时需要修改nginx中的配置
      #- ${WORDPRESS_UPLOADS_HOME}:/var/www/html/wp-content/uploads
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
  nginx:
    image: nginx:1.22.0
    container_name: nginx
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mynet
    depends_on:
      - wordpress
    ports:
      - 80:80    # http
      - 8443:8443    # https
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      # 读取wordpress中文件的路径
      #- ${WORDPRESS_UPLOADS_HOME}:/var/www/html/wp-content/uploads
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ${NGINX_SSL_PATH}:/etc/letsencrypt
      - ${NGINX_SSL_PATH}/live/${NGINX_SSL_HOST}:/etc/letsencrypt/ssl