server {
    listen 22226 proxy_protocol;
    listen 22220 http2 proxy_protocol;
    server_name  xray.ml520.me;
    #root /home/ubuntu/html;
    root /usr/share/nginx/html;
    index index.html index.htm;
}